### ISSUE TITLE
Failed to get channel with ID "X"

### ISSUE THREAD

**Issue by myshxd** [ErdbeerbaerLP/Discord-Integration-Fabric#17]
Everything is set up correctly. Worse it keeps wanting me to reauth when the bot was even on admin. idk

[Server thread/ERROR]: Failed to get channel with ID 'X', falling back to default channel
[27.11 04:06:21] [Server] [Thread-15/ERROR]: Failed to get channel with ID 'X', falling back to default channel
[27.11 04:06:21] [Server] [Thread-15/INFO]: [STDERR]: java.lang.IllegalStateException: Channel does not exist, check channel ID and bot permissions on both channel and category
[27.11 04:06:21] [Server] [Thread-15/INFO]: [STDERR]: 	at de.erdbeerbaerlp.dcintegration.common.storage.CommandRegistry.updateSlashCommands(CommandRegistry.java:37)
[27.11 04:06:21] [Server] [Thread-15/INFO]: [STDERR]: 	at de.erdbeerbaerlp.dcintegration.common.Discord.lambda$startThreads$9(Discord.java:447)
[27.11 04:06:21] [Server] [Thread-15/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ErdbeerbaerLP** [comment]
If you still have this issue, ask for help on discord. I can help you there
